version: '3.9'

services:
  app:
    build: ./
    environment:
      - PORT=3000
    volumes:
      - ./:/app
      - "nodeModules:/app/node_modules"
    ports:
      - "3000:3000"

volumes:
  nodeModules:
